# Generated by Django 5.0.2 on 2024-03-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Not Found'), to='myA.student')),
                ('student_identifier', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myA.studentid')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myA.subject')),
            ],
        ),
    ]
