# Generated by Django 5.0.2 on 2024-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myA', '0004_alter_student_student_id_alter_studentid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
