# Generated by Django 5.0.2 on 2024-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myA', '0006_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
