# Generated by Django 5.0.2 on 2024-03-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myA', '0007_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('departemnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myA.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myA.subject')),
            ],
        ),
    ]
